name: Aerotime Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn install

# test and build prior to release
      - name: Unit Test & Linting
        run: yarn test

      - name: Build
        run: yarn build

      - name: Release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: yarn publish --access public
